[package]
name = "tews_circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
poise = { version = "0.5.5" }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
rusqlite = { version = "0.29", features = ["bundled"] }
