INSERT INTO Ranks (Name)
SELECT 'Unrated' WHERE NOT EXISTS (SELECT 1 FROM Ranks WHERE Name = 'Unrated')
UNION
SELECT 'Gold' WHERE NOT EXISTS (SELECT 1 FROM Ranks WHERE Name = 'Gold')
UNION
SELECT 'Emerald' WHERE NOT EXISTS (SELECT 1 FROM Ranks WHERE Name = 'Emerald')
UNION
SELECT 'Diamond' WHERE NOT EXISTS (SELECT 1 FROM Ranks WHERE Name = 'Diamond');
